name: Adylan Roaffa
description: Software engineer by day, superhero by night.
meta_description: "Adylan Roaffa, tech blog"

aboutPage: true

markdown: kramdown
highlighter: rouge

plugins: 
    - jekyll-paginate
    - jekyll-seo-tag  
paginate: 20
domain_name: 'https://adylanroaffa.com'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# SEO tags
title: 'Adylan Roaffa'
description: 'Adylan Roaffa personal blog'
author: 'adylanrff'
twitter: 
    username: 'adylanrff'
    card: 'summary'
social:
  name: Adylan Roaffa Ilmyy
  links:
    - https://twitter.com/adylanrff
    - https://www.linkedin.com/in/adylan-roaffa
    - https://github.com/adylanrff

# Details for the RSS feed generator
url:            'https://adylanroaffa.com'
author:         'Adylan Roaffa'
authorTwitter:  'adylanrff'
authorGithub: 'adylanrff'
authorLinkedin: 'adylan-roaffa'

permalink:       /:title/

collections:
    portfolios:
        output: true

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
    -
        scope:
            path: ""
            type: portfolios
        values:
            layout: portfolio
